version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_persistent
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "app_db"       # 可选：初始数据库
      MYSQL_USER: "app_user"         # 可选：初始用户
      MYSQL_PASSWORD: "app_pass"     # 可选：用户密码
      TZ: "Asia/Shanghai"           # 时区设置
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

volumes:
  mysql_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/work/mysql/data                